### ISSUE TITLE
Any example using themoviedb-api

### ISSUE THREAD

**Issue by malasaad82** [18Months/themoviedb-api#12]
Hi,
Is there any example using themoviedb-api ?
How to set how to set the API and config? , I have created tmdb.rb in initializers folder and testing with irb and geting error:

Tmdb::Error (Invalid API key: You must be granted a valid key.)

Thanks

**Comment by malasaad82** [comment]
Here an example if anyone need
https://github.com/malasaad82/tmdb1

**Comment by samuelebistoletti** [comment]
Hi, 
in order to use TMDB you must have a valid API key, you can request it by registering an account here https://www.themoviedb.org/account. Then you have to initialize the gem with that API key, as shown on README.
