### ISSUE TITLE
Movie search issue / question

### ISSUE THREAD

**Issue by dancinglightning** [18Months/themoviedb-api#2]
Hi,
i've been looking at the tmdb gems and this one seems very good. I mean docs in place, coverage and according to my dabbling working very well.

But i was wondering, when i do a Search.movie("awakens")  i get back a Movie object.
But that movie object nevertheless looks nothing like a normal movie object, instead it has pages and result instances

This is somewhat confusing, maybe the search should return a Result object or something similar?

Tosten

**Comment by samuelebistoletti** [comment]
Hi,
you are undoubtedly right, we will fix this as soon as possibile.

**Comment by samuelebistoletti** [comment]
Hi, 
I fixed that here: https://github.com/18Months/themoviedb-api/commit/0515f1ac470760b49a7a932feb4bcce922e18f6b

I released a new version for this gem, please update to version 1.0.4
https://rubygems.org/gems/themoviedb-api
