### ISSUE TITLE
Cache Configuration

### ISSUE THREAD

**Issue by dancinglightning** [18Months/themoviedb-api#3]
Just a suggestion, but from the docs is wasn't clear to me that getting the configuration goes over the net.
So i was using it to get image path and was surprised how slow that was and found out.

As the config is unlikely to change during program execution i think it would be save to cache it.
And if the library doesn't it means every user has to.

**Comment by druzn3k** [comment]
You are right @dancinglightning, the configuration is unlikely to change, but here configuration is not "the" configuration, is an API endpoint. Mind you, I'm not against caching it, but in this case I think that caching it in the application is the way to go. Let's wait for @samuelebistoletti and see what he thinks about this issue.

**Comment by samuelebistoletti** [comment]
I agree with @druzn3k, the configuration is an API endpoint (http://docs.themoviedb.apiary.io/#reference/configuration/configuration) like others, and as such, in my opinion, it shouldn't be cached inside the gem, perhaps you would cache it inside your app as @druzn3k suggested.
