### ISSUE TITLE
Update gem version in Rubygems

### ISSUE THREAD

**Issue by brenda** [18Months/themoviedb-api#8]
Hi @druzn3k !

Could you please update the gem version to **1.2.0**  en [Rubygems](https://rubygems.org/gems/themoviedb-api)?

It would be great to have the updated version there.

Thanks!!

**Comment by druzn3k** [comment]
caaaaaaaan do! as soon as possible will be updated.

**Comment by samuelebistoletti** [comment]
New version pushed on Rubygems!

**Comment by brenda** [comment]
Excellent! Thanks!
